name: Mijn Open Catalogi Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update publiccode.yaml
        uses: OpenCatalogi/publiccode-action@1.1.1
      - name: Create een Productpagina
        uses: OpenCatalogi/productpage-action@1.0.0
        with:
          nl_design_theme_classname: "open-webconcept-theme"
          pull_from_branche: 'development'
          start_page: 'https://github.com/CommonGateway/NotificiationsBundle/blob/main/README.md'
          jumbotron_image_placement: "right"
          jumbotron_image_url: "https://raw.githubusercontent.com/OpenWebconcept/.github/main/docs/componenten.svg"
